name = "doc-converter"
main = "src/index.js"
compatibility_date = "2024-01-01"

# Binding ke R2 Bucket (Pastikan bucket 'doc-convert-bucket' sudah dibuat)
[[r2_buckets]]
binding = "MY_BUCKET"
bucket_name = "doc-convert-bucket"

[[rules]]
type = "Text"
globs = ["**/*.html", "**/*.css", "**/*.js"]
